import React from 'react'
import './BookingProcess.css'
import Image from 'next/image'
import exploreicon from '../../Assets/homepageassets/exploreicon.png'
import bg_oneimge from '../../Assets/homepageassets/bg_oneimge.png'
import bg_twoimge from '../../Assets/homepageassets/bg_twoimge.png'
import bg_threeimge from '../../Assets/homepageassets/bg_threeimge.png'
const Bookingprocess = () => {
    return (
        <>
            <div className='booking_process_text' >
                <p className='chooseexperience' >Why Book With Us</p>
                <h5 className='topdestination' >Convenient and Easy Tour Booking Process</h5>
            </div>

            <div className='bg_conatiner' >

                <div className='bg_one_container' >
                    <Image src={bg_oneimge} alt='bg_oneimge' />
                    <div className='selection_tours' >
                        <h1 className='wide_selection_text' >Wide Selection of Tours</h1>
                        <p className='wide_selection_text_p' >Offering tours in 130+ countries and on all continents, allows you to easily find and book your favourite day tours and package tours.</p>
                    </div>

                    <div className='exploreNow_btn_container'>
                        <button style={{ backgroundColor: 'transparent', color: 'white', border: '1px solid white' }} className='exploreNow_btn   mt-4' >Explore Now <Image src={exploreicon} alt='exploreicon' /></button>
                    </div>
                </div>

                <div className='bg_two_container' >
                    <Image src={bg_twoimge} alt='bg_twoimge' />
                    <div className='selection_tours' >
                        <h1 className='wide_selection_text' >Fast Booking</h1>
                        <p className='wide_selection_text_p' >OZourney is automatically offsetting the carbon footprint generated by all tour bookings, for online package tour booking platforms.</p>
                    </div>

                    <div className='exploreNow_btn_container'>
                        <button style={{ backgroundColor: 'transparent', color: 'white', border: '1px solid white' }} className='exploreNow_btn   mt-4' >Explore Now <Image src={exploreicon} alt='exploreicon' /></button>
                    </div>
                </div>

                <div className='bg_three_container' >
                    <Image src={bg_threeimge} alt='bg_threeimge' />
                    <div className='selection_tours' >
                        <h1 className='wide_selection_text' >Pesonalized Trips</h1>
                        <p className='wide_selection_text_p' >Our local travel experts will design a trip that matches your unique interests and special requirements, booking everything.</p>
                    </div>

                    <div className='exploreNow_btn_container'>
                        <button style={{ backgroundColor: 'transparent', color: 'white', border: '1px solid white' }} className='exploreNow_btn   mt-4' >Explore Now <Image src={exploreicon} alt='exploreicon' /></button>
                    </div>
                </div>



            </div>

        </>
    )
}

export default Bookingprocess